image:                                                                                                                                                                                                                   
  name: amazon/aws-cli:latest                                                                                                                                                                                            
  entrypoint: [""]

stages:
  - test
  - build
  - deploy

run_unit_tests:
  stage: test
  before_script:
    - echo "Preparing for testing......"
    - test -n "$AWS_ACCESS_KEY_ID" || { echo "AWS_ACCESS_KEY_ID is required"; exit 1; }
    - test -n "$AWS_SECRET_ACCESS_KEY" || { echo "AWS_SECRET_ACCESS_KEY is required"; exit 1; }
    - sed -i 's/\r$//' subnet.sh    # Remove Windows line endings
    - chmod +x subnet.sh
    - aws --version
    - aws sts get-caller-identity
    - yum install -y python3 python3-pip 
    - pip3 install awscli
    - aws --version
    - aws sts get-caller-identity

  script:
    - echo "Ensuring subnet.sh is available"
    - if [ ! -f ./subnet.sh ]; then echo "Error:subnet.sh not found"; exit 1; fi
    - REGION_INPUT="${AWS_REGION:-us-east-1}"
    - VPC_CIDR="${VPC_CIDR:-10.0.0.0/16}"
    - printf '%s\n%s\n' "$REGION_INPUT" "$VPC_CIDR" | ./subnet.sh
    - echo "Script completed with exit code:$?"

  after_script:
    - echo "Cleaning up temporary files......"
