stages:
  - user_data
  - verification
  - testing
  - deployment

variables:
  AWS_REGION: "us-east-1"

user_data:
  stage: user_data
  image: alpine:3.19
  script:
    - echo "Preparing launch template user data"
    - apk add --no-cache curl
    - curl -sSf https://newerabucket2026.s3.us-east-1.amazonaws.com/userdataraw.sh -o userdataraw.sh
    - test -s userdataraw.sh
  artifacts:
    paths:
      - userdataraw.sh
    expire_in: 1 day

verification:
  stage: verification
  image: alpine:3.19
  dependencies:
    - user_data
  script:
    - apk add --no-cache grep
    - |
      grep -q "curl -fsSL" userdataraw.sh || {
        echo "Missing curl download step" >&2;
        exit 1;
      }
    - |
      for var in DB_HOST DB_USER DB_PASS DB_NAME; do
        grep -q "$var" userdataraw.sh || {
          echo "Missing expected export: $var" >&2;
          exit 1;
        };
      done
    - echo "user_data verification passed"

unit_tests:
  stage: testing
  image: amazonlinux:2023
  dependencies:
    - user_data
  before_script:
    - dnf -y install php-cli php-mysqlnd > /dev/null
  script:
    - php -l /var/www/html/comics/lib/app.php || echo 'php lint skipped (file not present in CI image)'
    - echo "No unit tests defined yet"
  allow_failure: true

deployment:
  stage: deployment
  image: alpine:3.19
  dependencies:
    - user_data
  script:
    - echo "Deployment stage placeholder"
    - echo "Use awscli here once credentials are available"
  when: manual
  environment:
    name: production
